version: "3.8"
services:
  server:
    build: .
    container_name: carmelton_server
    env_file:
      - .env.production
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - client

  client:
    build:
      context: ./client
      args:
        REACT_APP_API_URL: "http://localhost:3002"
        # הוסף כאן משתנים נוספים אם צריך
    container_name: carmelton_client
    ports:
      - "3000:80"
    restart: always
